version: '3.8'  # Update to a supported version

services:
  minecraft_server:
    build:
      context: .
    ports:
      - "25565:25565"
      - "25575:25575"
      - "19132:19132/udp"
      - "19133:19133/udp"
    volumes:
      - ./data:/data
    environment:
      - EULA=TRUE
      - ONLINE_MODE=FALSE