version: '3.8'

services:
  saturns_orbit:
    build: .
    image: cdaprod/saturns_orbit:latest
    container_name: saturns_orbit
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    volumes:
      - ./maps:/maps
    environment:
      - EULA=TRUE
      - WORLD_NAME=saturns_orbit

  bessemer_city:
    build: .
    image: cdaprod/bessemer_city:latest
    container_name: bessemer_city
    ports:
      - "19134:19134/udp"
      - "19135:19135/udp"
    volumes:
      - ./maps:/maps
    environment:
      - EULA=TRUE
      - WORLD_NAME=bessemer_city

  blue_tide:
    build: .
    image: cdaprod/blue_tide:latest
    container_name: blue_tide
    ports:
      - "19136:19136/udp"
      - "19137:19137/udp"
    volumes:
      - ./maps:/maps
    environment:
      - EULA=TRUE
      - WORLD_NAME=blue_tide